[package]
name = "rust_hls"
version = "0.1.0"
authors = ["Zev Stravitz <zevstravitz@verizon.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gotham = "0.6.0"